<?php $e = static fn (mixed $v): string => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8'); $assigned = $user?->roles?->pluck('id')->map(fn ($id) => (int) $id)->all() ?? []; ?>
<div class="mx-auto max-w-3xl space-y-6"><div><h1 class="text-2xl font-bold text-slate-900 dark:text-white"><?= $e($title) ?></h1><a class="text-sm text-indigo-600" href="/admin/authentication/users">← Към потребителите</a></div>
<form method="post" action="<?= $user ? '/admin/authentication/users/' . (int) $user->id : '/admin/authentication/users' ?>" class="space-y-6 rounded-xl border border-slate-200 bg-white p-6 dark:border-slate-700 dark:bg-slate-800">
  <label class="block text-sm font-semibold">Име<input required name="fullname" value="<?= $e($user?->fullname) ?>" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5 dark:bg-slate-900"></label>
  <label class="block text-sm font-semibold">Имейл<input required type="email" name="email" value="<?= $e($user?->email) ?>" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5 dark:bg-slate-900"></label>
  <label class="block text-sm font-semibold">Парола <?= $user ? '(оставете празно без промяна)' : '' ?><input <?= $user ? '' : 'required' ?> minlength="12" type="password" name="password" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5 dark:bg-slate-900"></label>
  <div class="flex gap-6"><label><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" <?= !$user || $user->is_active ? 'checked' : '' ?>> Активен</label><label><input type="hidden" name="is_super_admin" value="0"><input type="checkbox" name="is_super_admin" value="1" <?= $user?->is_super_admin ? 'checked' : '' ?>> Супер администратор</label></div>
  <fieldset><legend class="mb-2 font-semibold">Роли</legend><div class="grid gap-2 sm:grid-cols-2"><?php foreach ($roles as $role): ?><label class="rounded-lg border p-3"><input type="checkbox" name="roles[]" value="<?= (int) $role->id ?>" <?= in_array((int) $role->id, $assigned, true) ? 'checked' : '' ?>> <?= $e($role->name) ?></label><?php endforeach; ?></div></fieldset>
  <div class="flex justify-between"><button class="rounded-lg bg-indigo-600 px-5 py-2.5 font-semibold text-white">Запази</button><?php if ($user && !$user->is_super_admin): ?><button form="delete-user" class="rounded-lg border border-red-300 px-4 py-2 text-red-700">Изтрий</button><?php endif; ?></div>
</form><?php if ($user && !$user->is_super_admin): ?><form id="delete-user" method="post" action="/admin/authentication/users/<?= (int) $user->id ?>/delete"></form><?php endif; ?></div>
